module.exports = {
    dsa: [
        // "ArrayList",
        // "BFSGraphList",
        // "BFSGraphMatrix",
        // "BTBFS",
        // "BTInOrder",
        // "BTPostOrder",
        // "BTPreOrder",
        // "BinarySearchList",
        // "BubbleSort",
        // "CoinChange",
        "CompareBinaryTrees",
        "DFSGraphList",
        "DFSOnBST",
        // "DailyTemperatures",
        // "DijkstraList",
        // "DoublyLinkedList",
        // "FenwickTree",
        // "FindMinRotatedSorted",
        // "HasCycle",
        // "HashSet",
        // "InsertionSort",
        // "InvertTree",
        // "KMP",
        // "KadanesAlgorithm",
        // "Knapsack",
        // "Kruskals",
        // "KthLargest",
        // "LRU",
        // "LinearSearchList",
        // "LongestCommonSubsequence",
        // "Map",
        // "MazeSolver",
        // "MedianFinder",
        // "MergeRanges",
        // "MergeSort",
        // "MinHeap",
        // "PrimsList",
        // "Queue",
        // "QuickSort",
        // "RingBuffer",
        // "SegmentTree",
        // "SinglyLinkedList",
        // "SlidingWindowMax",
        // "Stack",
        // "Subsets",
        // "TopologicalSort",
        // "Trie",
        // "TwoCrystalBalls",
        // "TwoSumSorted",
        // "UnionFind",
    ],
}
