module.exports = {
    dsa: [
        // "ArrayList",
        "AsyncQueue",
        // "BFSGraphList",
        // "BFSGraphMatrix",
        "BTBFS",
        // "BTInOrder",
        // "BTPostOrder",
        // "BTPreOrder",
        // "BinarySearchList",
        // "BubbleSort",
        // "CoinChange",
        // "CompareBinaryTrees",
        // "DFSGraphList",
        // "DFSOnBST",
        // "DailyTemperatures",
        "DijkstraList",
        // "DoublyLinkedList",
        // "FenwickTree",
        // "FindMinRotatedSorted",
        // "HasCycle",
        // "HashSet",
        // "InsertionSort",
        // "Knapsack",
        // "KthLargest",
        // "LRU",
        // "LinearSearchList",
        // "LongestCommonSubsequence",
        // "Map",
        // "MazeSolver",
        // "MedianFinder",
        // "MergeRanges",
        // "MergeSort",
        // "MinHeap",
        // "PrimsList",
        // "QuadTree",
        // "Queue",
        // "QuickSort",
        // "RingBuffer",
        // "RoundRobin",
        // "SegmentTree",
        // "SinglyLinkedList",
        // "SlidingWindowMax",
        // "Stack",
        // "Subsets",
        // "TopologicalSort",
        // "Trie",
        // "TwoCrystalBalls",
        // "TwoSumSorted",
        // "UnionFind",
    ],
}
